/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RpgRulesRouteImport } from './routes/rpg-rules'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsStoryPinsRouteImport } from './routes/campaigns.story-pins'
import { Route as CampaignsNpcCharactersRouteImport } from './routes/campaigns.npc-characters'
import { Route as CampaignsMapBuilderRouteImport } from './routes/campaigns.map-builder'
import { Route as CampaignsGameTimelineRouteImport } from './routes/campaigns.game-timeline'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'

const RpgRulesRoute = RpgRulesRouteImport.update({
  id: '/rpg-rules',
  path: '/rpg-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsStoryPinsRoute = CampaignsStoryPinsRouteImport.update({
  id: '/story-pins',
  path: '/story-pins',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsNpcCharactersRoute = CampaignsNpcCharactersRouteImport.update({
  id: '/npc-characters',
  path: '/npc-characters',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsMapBuilderRoute = CampaignsMapBuilderRouteImport.update({
  id: '/map-builder',
  path: '/map-builder',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsGameTimelineRoute = CampaignsGameTimelineRouteImport.update({
  id: '/game-timeline',
  path: '/game-timeline',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => CampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/rpg-rules': typeof RpgRulesRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/game-timeline': typeof CampaignsGameTimelineRoute
  '/campaigns/map-builder': typeof CampaignsMapBuilderRoute
  '/campaigns/npc-characters': typeof CampaignsNpcCharactersRoute
  '/campaigns/story-pins': typeof CampaignsStoryPinsRoute
  '/campaigns/': typeof CampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rpg-rules': typeof RpgRulesRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/game-timeline': typeof CampaignsGameTimelineRoute
  '/campaigns/map-builder': typeof CampaignsMapBuilderRoute
  '/campaigns/npc-characters': typeof CampaignsNpcCharactersRoute
  '/campaigns/story-pins': typeof CampaignsStoryPinsRoute
  '/campaigns': typeof CampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/rpg-rules': typeof RpgRulesRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/game-timeline': typeof CampaignsGameTimelineRoute
  '/campaigns/map-builder': typeof CampaignsMapBuilderRoute
  '/campaigns/npc-characters': typeof CampaignsNpcCharactersRoute
  '/campaigns/story-pins': typeof CampaignsStoryPinsRoute
  '/campaigns/': typeof CampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/rpg-rules'
    | '/campaigns/$campaignId'
    | '/campaigns/game-timeline'
    | '/campaigns/map-builder'
    | '/campaigns/npc-characters'
    | '/campaigns/story-pins'
    | '/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rpg-rules'
    | '/campaigns/$campaignId'
    | '/campaigns/game-timeline'
    | '/campaigns/map-builder'
    | '/campaigns/npc-characters'
    | '/campaigns/story-pins'
    | '/campaigns'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/rpg-rules'
    | '/campaigns/$campaignId'
    | '/campaigns/game-timeline'
    | '/campaigns/map-builder'
    | '/campaigns/npc-characters'
    | '/campaigns/story-pins'
    | '/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  RpgRulesRoute: typeof RpgRulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rpg-rules': {
      id: '/rpg-rules'
      path: '/rpg-rules'
      fullPath: '/rpg-rules'
      preLoaderRoute: typeof RpgRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/story-pins': {
      id: '/campaigns/story-pins'
      path: '/story-pins'
      fullPath: '/campaigns/story-pins'
      preLoaderRoute: typeof CampaignsStoryPinsRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/npc-characters': {
      id: '/campaigns/npc-characters'
      path: '/npc-characters'
      fullPath: '/campaigns/npc-characters'
      preLoaderRoute: typeof CampaignsNpcCharactersRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/map-builder': {
      id: '/campaigns/map-builder'
      path: '/map-builder'
      fullPath: '/campaigns/map-builder'
      preLoaderRoute: typeof CampaignsMapBuilderRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/game-timeline': {
      id: '/campaigns/game-timeline'
      path: '/game-timeline'
      fullPath: '/campaigns/game-timeline'
      preLoaderRoute: typeof CampaignsGameTimelineRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
  }
}

interface CampaignsRouteChildren {
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  CampaignsGameTimelineRoute: typeof CampaignsGameTimelineRoute
  CampaignsMapBuilderRoute: typeof CampaignsMapBuilderRoute
  CampaignsNpcCharactersRoute: typeof CampaignsNpcCharactersRoute
  CampaignsStoryPinsRoute: typeof CampaignsStoryPinsRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  CampaignsGameTimelineRoute: CampaignsGameTimelineRoute,
  CampaignsMapBuilderRoute: CampaignsMapBuilderRoute,
  CampaignsNpcCharactersRoute: CampaignsNpcCharactersRoute,
  CampaignsStoryPinsRoute: CampaignsStoryPinsRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  RpgRulesRoute: RpgRulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
