/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RpgsRouteImport } from './routes/rpgs'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RpgsIndexRouteImport } from './routes/rpgs.index'
import { Route as MapsIndexRouteImport } from './routes/maps.index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as RpgsDndRouteImport } from './routes/rpgs.dnd'
import { Route as MapsMapIdRouteImport } from './routes/maps.$mapId'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as CampaignsCampaignIdIndexRouteImport } from './routes/campaigns.$campaignId.index'
import { Route as CampaignsCampaignIdWorkspaceRouteImport } from './routes/campaigns.$campaignId.workspace'
import { Route as CampaignsCampaignIdNpcDatabaseRouteImport } from './routes/campaigns.$campaignId.npc-database'
import { Route as CampaignsCampaignIdLoreSecretsDatabaseRouteImport } from './routes/campaigns.$campaignId.lore-secrets-database'
import { Route as CampaignsCampaignIdEncounterLibraryRouteImport } from './routes/campaigns.$campaignId.encounter-library'
import { Route as CampaignsCampaignIdWorkspaceIndexRouteImport } from './routes/campaigns.$campaignId.workspace.index'
import { Route as CampaignsCampaignIdWorkspaceSessionsRouteImport } from './routes/campaigns.$campaignId.workspace.sessions'
import { Route as CampaignsCampaignIdWorkspaceSecretsRouteImport } from './routes/campaigns.$campaignId.workspace.secrets'
import { Route as CampaignsCampaignIdWorkspaceSceneNotesRouteImport } from './routes/campaigns.$campaignId.workspace.scene-notes'
import { Route as CampaignsCampaignIdWorkspacePlayerCharactersRouteImport } from './routes/campaigns.$campaignId.workspace.player-characters'
import { Route as CampaignsCampaignIdWorkspaceNpcsRouteImport } from './routes/campaigns.$campaignId.workspace.npcs'
import { Route as CampaignsCampaignIdWorkspaceLogRouteImport } from './routes/campaigns.$campaignId.workspace.log'
import { Route as CampaignsCampaignIdWorkspaceEncountersRouteImport } from './routes/campaigns.$campaignId.workspace.encounters'
import { Route as CampaignsCampaignIdWorkspaceDmScreenRouteImport } from './routes/campaigns.$campaignId.workspace.dm-screen'
import { Route as CampaignsCampaignIdWorkspaceSessionsIndexRouteImport } from './routes/campaigns.$campaignId.workspace.sessions.index'
import { Route as CampaignsCampaignIdWorkspacePlayerCharactersIndexRouteImport } from './routes/campaigns.$campaignId.workspace.player-characters.index'
import { Route as CampaignsCampaignIdWorkspaceSessionsSessionIdRouteImport } from './routes/campaigns.$campaignId.workspace.sessions.$sessionId'
import { Route as CampaignsCampaignIdWorkspacePlayerCharactersPlayerCharacterIdRouteImport } from './routes/campaigns.$campaignId.workspace.player-characters.$playerCharacterId'

const RpgsRoute = RpgsRouteImport.update({
  id: '/rpgs',
  path: '/rpgs',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpgsIndexRoute = RpgsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RpgsRoute,
} as any)
const MapsIndexRoute = MapsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapsRoute,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const RpgsDndRoute = RpgsDndRouteImport.update({
  id: '/dnd',
  path: '/dnd',
  getParentRoute: () => RpgsRoute,
} as any)
const MapsMapIdRoute = MapsMapIdRouteImport.update({
  id: '/$mapId',
  path: '/$mapId',
  getParentRoute: () => MapsRoute,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsCampaignIdIndexRoute =
  CampaignsCampaignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdWorkspaceRoute =
  CampaignsCampaignIdWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdNpcDatabaseRoute =
  CampaignsCampaignIdNpcDatabaseRouteImport.update({
    id: '/npc-database',
    path: '/npc-database',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdLoreSecretsDatabaseRoute =
  CampaignsCampaignIdLoreSecretsDatabaseRouteImport.update({
    id: '/lore-secrets-database',
    path: '/lore-secrets-database',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdEncounterLibraryRoute =
  CampaignsCampaignIdEncounterLibraryRouteImport.update({
    id: '/encounter-library',
    path: '/encounter-library',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdWorkspaceIndexRoute =
  CampaignsCampaignIdWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdWorkspaceRoute,
  } as any)
const CampaignsCampaignIdWorkspaceSessionsRoute =
  CampaignsCampaignIdWorkspaceSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => CampaignsCampaignIdWorkspaceRoute,
  } as any)
const CampaignsCampaignIdWorkspaceSecretsRoute =
  CampaignsCampaignIdWorkspaceSecretsRouteImport.update({
    id: '/secrets',
    path: '/secrets',
    getParentRoute: () => CampaignsCampaignIdWorkspaceRoute,
  } as any)
const CampaignsCampaignIdWorkspaceSceneNotesRoute =
  CampaignsCampaignIdWorkspaceSceneNotesRouteImport.update({
    id: '/scene-notes',
    path: '/scene-notes',
    getParentRoute: () => CampaignsCampaignIdWorkspaceRoute,
  } as any)
const CampaignsCampaignIdWorkspacePlayerCharactersRoute =
  CampaignsCampaignIdWorkspacePlayerCharactersRouteImport.update({
    id: '/player-characters',
    path: '/player-characters',
    getParentRoute: () => CampaignsCampaignIdWorkspaceRoute,
  } as any)
const CampaignsCampaignIdWorkspaceNpcsRoute =
  CampaignsCampaignIdWorkspaceNpcsRouteImport.update({
    id: '/npcs',
    path: '/npcs',
    getParentRoute: () => CampaignsCampaignIdWorkspaceRoute,
  } as any)
const CampaignsCampaignIdWorkspaceLogRoute =
  CampaignsCampaignIdWorkspaceLogRouteImport.update({
    id: '/log',
    path: '/log',
    getParentRoute: () => CampaignsCampaignIdWorkspaceRoute,
  } as any)
const CampaignsCampaignIdWorkspaceEncountersRoute =
  CampaignsCampaignIdWorkspaceEncountersRouteImport.update({
    id: '/encounters',
    path: '/encounters',
    getParentRoute: () => CampaignsCampaignIdWorkspaceRoute,
  } as any)
const CampaignsCampaignIdWorkspaceDmScreenRoute =
  CampaignsCampaignIdWorkspaceDmScreenRouteImport.update({
    id: '/dm-screen',
    path: '/dm-screen',
    getParentRoute: () => CampaignsCampaignIdWorkspaceRoute,
  } as any)
const CampaignsCampaignIdWorkspaceSessionsIndexRoute =
  CampaignsCampaignIdWorkspaceSessionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdWorkspaceSessionsRoute,
  } as any)
const CampaignsCampaignIdWorkspacePlayerCharactersIndexRoute =
  CampaignsCampaignIdWorkspacePlayerCharactersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdWorkspacePlayerCharactersRoute,
  } as any)
const CampaignsCampaignIdWorkspaceSessionsSessionIdRoute =
  CampaignsCampaignIdWorkspaceSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => CampaignsCampaignIdWorkspaceSessionsRoute,
  } as any)
const CampaignsCampaignIdWorkspacePlayerCharactersPlayerCharacterIdRoute =
  CampaignsCampaignIdWorkspacePlayerCharactersPlayerCharacterIdRouteImport.update(
    {
      id: '/$playerCharacterId',
      path: '/$playerCharacterId',
      getParentRoute: () => CampaignsCampaignIdWorkspacePlayerCharactersRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/maps': typeof MapsRouteWithChildren
  '/rpgs': typeof RpgsRouteWithChildren
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/maps/$mapId': typeof MapsMapIdRoute
  '/rpgs/dnd': typeof RpgsDndRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/rpgs/': typeof RpgsIndexRoute
  '/campaigns/$campaignId/encounter-library': typeof CampaignsCampaignIdEncounterLibraryRoute
  '/campaigns/$campaignId/lore-secrets-database': typeof CampaignsCampaignIdLoreSecretsDatabaseRoute
  '/campaigns/$campaignId/npc-database': typeof CampaignsCampaignIdNpcDatabaseRoute
  '/campaigns/$campaignId/workspace': typeof CampaignsCampaignIdWorkspaceRouteWithChildren
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
  '/campaigns/$campaignId/workspace/dm-screen': typeof CampaignsCampaignIdWorkspaceDmScreenRoute
  '/campaigns/$campaignId/workspace/encounters': typeof CampaignsCampaignIdWorkspaceEncountersRoute
  '/campaigns/$campaignId/workspace/log': typeof CampaignsCampaignIdWorkspaceLogRoute
  '/campaigns/$campaignId/workspace/npcs': typeof CampaignsCampaignIdWorkspaceNpcsRoute
  '/campaigns/$campaignId/workspace/player-characters': typeof CampaignsCampaignIdWorkspacePlayerCharactersRouteWithChildren
  '/campaigns/$campaignId/workspace/scene-notes': typeof CampaignsCampaignIdWorkspaceSceneNotesRoute
  '/campaigns/$campaignId/workspace/secrets': typeof CampaignsCampaignIdWorkspaceSecretsRoute
  '/campaigns/$campaignId/workspace/sessions': typeof CampaignsCampaignIdWorkspaceSessionsRouteWithChildren
  '/campaigns/$campaignId/workspace/': typeof CampaignsCampaignIdWorkspaceIndexRoute
  '/campaigns/$campaignId/workspace/player-characters/$playerCharacterId': typeof CampaignsCampaignIdWorkspacePlayerCharactersPlayerCharacterIdRoute
  '/campaigns/$campaignId/workspace/sessions/$sessionId': typeof CampaignsCampaignIdWorkspaceSessionsSessionIdRoute
  '/campaigns/$campaignId/workspace/player-characters/': typeof CampaignsCampaignIdWorkspacePlayerCharactersIndexRoute
  '/campaigns/$campaignId/workspace/sessions/': typeof CampaignsCampaignIdWorkspaceSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/rpgs/dnd': typeof RpgsDndRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/maps': typeof MapsIndexRoute
  '/rpgs': typeof RpgsIndexRoute
  '/campaigns/$campaignId/encounter-library': typeof CampaignsCampaignIdEncounterLibraryRoute
  '/campaigns/$campaignId/lore-secrets-database': typeof CampaignsCampaignIdLoreSecretsDatabaseRoute
  '/campaigns/$campaignId/npc-database': typeof CampaignsCampaignIdNpcDatabaseRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdIndexRoute
  '/campaigns/$campaignId/workspace/dm-screen': typeof CampaignsCampaignIdWorkspaceDmScreenRoute
  '/campaigns/$campaignId/workspace/encounters': typeof CampaignsCampaignIdWorkspaceEncountersRoute
  '/campaigns/$campaignId/workspace/log': typeof CampaignsCampaignIdWorkspaceLogRoute
  '/campaigns/$campaignId/workspace/npcs': typeof CampaignsCampaignIdWorkspaceNpcsRoute
  '/campaigns/$campaignId/workspace/scene-notes': typeof CampaignsCampaignIdWorkspaceSceneNotesRoute
  '/campaigns/$campaignId/workspace/secrets': typeof CampaignsCampaignIdWorkspaceSecretsRoute
  '/campaigns/$campaignId/workspace': typeof CampaignsCampaignIdWorkspaceIndexRoute
  '/campaigns/$campaignId/workspace/player-characters/$playerCharacterId': typeof CampaignsCampaignIdWorkspacePlayerCharactersPlayerCharacterIdRoute
  '/campaigns/$campaignId/workspace/sessions/$sessionId': typeof CampaignsCampaignIdWorkspaceSessionsSessionIdRoute
  '/campaigns/$campaignId/workspace/player-characters': typeof CampaignsCampaignIdWorkspacePlayerCharactersIndexRoute
  '/campaigns/$campaignId/workspace/sessions': typeof CampaignsCampaignIdWorkspaceSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/maps': typeof MapsRouteWithChildren
  '/rpgs': typeof RpgsRouteWithChildren
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/maps/$mapId': typeof MapsMapIdRoute
  '/rpgs/dnd': typeof RpgsDndRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/rpgs/': typeof RpgsIndexRoute
  '/campaigns/$campaignId/encounter-library': typeof CampaignsCampaignIdEncounterLibraryRoute
  '/campaigns/$campaignId/lore-secrets-database': typeof CampaignsCampaignIdLoreSecretsDatabaseRoute
  '/campaigns/$campaignId/npc-database': typeof CampaignsCampaignIdNpcDatabaseRoute
  '/campaigns/$campaignId/workspace': typeof CampaignsCampaignIdWorkspaceRouteWithChildren
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
  '/campaigns/$campaignId/workspace/dm-screen': typeof CampaignsCampaignIdWorkspaceDmScreenRoute
  '/campaigns/$campaignId/workspace/encounters': typeof CampaignsCampaignIdWorkspaceEncountersRoute
  '/campaigns/$campaignId/workspace/log': typeof CampaignsCampaignIdWorkspaceLogRoute
  '/campaigns/$campaignId/workspace/npcs': typeof CampaignsCampaignIdWorkspaceNpcsRoute
  '/campaigns/$campaignId/workspace/player-characters': typeof CampaignsCampaignIdWorkspacePlayerCharactersRouteWithChildren
  '/campaigns/$campaignId/workspace/scene-notes': typeof CampaignsCampaignIdWorkspaceSceneNotesRoute
  '/campaigns/$campaignId/workspace/secrets': typeof CampaignsCampaignIdWorkspaceSecretsRoute
  '/campaigns/$campaignId/workspace/sessions': typeof CampaignsCampaignIdWorkspaceSessionsRouteWithChildren
  '/campaigns/$campaignId/workspace/': typeof CampaignsCampaignIdWorkspaceIndexRoute
  '/campaigns/$campaignId/workspace/player-characters/$playerCharacterId': typeof CampaignsCampaignIdWorkspacePlayerCharactersPlayerCharacterIdRoute
  '/campaigns/$campaignId/workspace/sessions/$sessionId': typeof CampaignsCampaignIdWorkspaceSessionsSessionIdRoute
  '/campaigns/$campaignId/workspace/player-characters/': typeof CampaignsCampaignIdWorkspacePlayerCharactersIndexRoute
  '/campaigns/$campaignId/workspace/sessions/': typeof CampaignsCampaignIdWorkspaceSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/maps'
    | '/rpgs'
    | '/campaigns/$campaignId'
    | '/maps/$mapId'
    | '/rpgs/dnd'
    | '/campaigns/'
    | '/maps/'
    | '/rpgs/'
    | '/campaigns/$campaignId/encounter-library'
    | '/campaigns/$campaignId/lore-secrets-database'
    | '/campaigns/$campaignId/npc-database'
    | '/campaigns/$campaignId/workspace'
    | '/campaigns/$campaignId/'
    | '/campaigns/$campaignId/workspace/dm-screen'
    | '/campaigns/$campaignId/workspace/encounters'
    | '/campaigns/$campaignId/workspace/log'
    | '/campaigns/$campaignId/workspace/npcs'
    | '/campaigns/$campaignId/workspace/player-characters'
    | '/campaigns/$campaignId/workspace/scene-notes'
    | '/campaigns/$campaignId/workspace/secrets'
    | '/campaigns/$campaignId/workspace/sessions'
    | '/campaigns/$campaignId/workspace/'
    | '/campaigns/$campaignId/workspace/player-characters/$playerCharacterId'
    | '/campaigns/$campaignId/workspace/sessions/$sessionId'
    | '/campaigns/$campaignId/workspace/player-characters/'
    | '/campaigns/$campaignId/workspace/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/maps/$mapId'
    | '/rpgs/dnd'
    | '/campaigns'
    | '/maps'
    | '/rpgs'
    | '/campaigns/$campaignId/encounter-library'
    | '/campaigns/$campaignId/lore-secrets-database'
    | '/campaigns/$campaignId/npc-database'
    | '/campaigns/$campaignId'
    | '/campaigns/$campaignId/workspace/dm-screen'
    | '/campaigns/$campaignId/workspace/encounters'
    | '/campaigns/$campaignId/workspace/log'
    | '/campaigns/$campaignId/workspace/npcs'
    | '/campaigns/$campaignId/workspace/scene-notes'
    | '/campaigns/$campaignId/workspace/secrets'
    | '/campaigns/$campaignId/workspace'
    | '/campaigns/$campaignId/workspace/player-characters/$playerCharacterId'
    | '/campaigns/$campaignId/workspace/sessions/$sessionId'
    | '/campaigns/$campaignId/workspace/player-characters'
    | '/campaigns/$campaignId/workspace/sessions'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/maps'
    | '/rpgs'
    | '/campaigns/$campaignId'
    | '/maps/$mapId'
    | '/rpgs/dnd'
    | '/campaigns/'
    | '/maps/'
    | '/rpgs/'
    | '/campaigns/$campaignId/encounter-library'
    | '/campaigns/$campaignId/lore-secrets-database'
    | '/campaigns/$campaignId/npc-database'
    | '/campaigns/$campaignId/workspace'
    | '/campaigns/$campaignId/'
    | '/campaigns/$campaignId/workspace/dm-screen'
    | '/campaigns/$campaignId/workspace/encounters'
    | '/campaigns/$campaignId/workspace/log'
    | '/campaigns/$campaignId/workspace/npcs'
    | '/campaigns/$campaignId/workspace/player-characters'
    | '/campaigns/$campaignId/workspace/scene-notes'
    | '/campaigns/$campaignId/workspace/secrets'
    | '/campaigns/$campaignId/workspace/sessions'
    | '/campaigns/$campaignId/workspace/'
    | '/campaigns/$campaignId/workspace/player-characters/$playerCharacterId'
    | '/campaigns/$campaignId/workspace/sessions/$sessionId'
    | '/campaigns/$campaignId/workspace/player-characters/'
    | '/campaigns/$campaignId/workspace/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  MapsRoute: typeof MapsRouteWithChildren
  RpgsRoute: typeof RpgsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rpgs': {
      id: '/rpgs'
      path: '/rpgs'
      fullPath: '/rpgs'
      preLoaderRoute: typeof RpgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpgs/': {
      id: '/rpgs/'
      path: '/'
      fullPath: '/rpgs/'
      preLoaderRoute: typeof RpgsIndexRouteImport
      parentRoute: typeof RpgsRoute
    }
    '/maps/': {
      id: '/maps/'
      path: '/'
      fullPath: '/maps/'
      preLoaderRoute: typeof MapsIndexRouteImport
      parentRoute: typeof MapsRoute
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/rpgs/dnd': {
      id: '/rpgs/dnd'
      path: '/dnd'
      fullPath: '/rpgs/dnd'
      preLoaderRoute: typeof RpgsDndRouteImport
      parentRoute: typeof RpgsRoute
    }
    '/maps/$mapId': {
      id: '/maps/$mapId'
      path: '/$mapId'
      fullPath: '/maps/$mapId'
      preLoaderRoute: typeof MapsMapIdRouteImport
      parentRoute: typeof MapsRoute
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/$campaignId/': {
      id: '/campaigns/$campaignId/'
      path: '/'
      fullPath: '/campaigns/$campaignId/'
      preLoaderRoute: typeof CampaignsCampaignIdIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/workspace': {
      id: '/campaigns/$campaignId/workspace'
      path: '/workspace'
      fullPath: '/campaigns/$campaignId/workspace'
      preLoaderRoute: typeof CampaignsCampaignIdWorkspaceRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/npc-database': {
      id: '/campaigns/$campaignId/npc-database'
      path: '/npc-database'
      fullPath: '/campaigns/$campaignId/npc-database'
      preLoaderRoute: typeof CampaignsCampaignIdNpcDatabaseRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/lore-secrets-database': {
      id: '/campaigns/$campaignId/lore-secrets-database'
      path: '/lore-secrets-database'
      fullPath: '/campaigns/$campaignId/lore-secrets-database'
      preLoaderRoute: typeof CampaignsCampaignIdLoreSecretsDatabaseRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/encounter-library': {
      id: '/campaigns/$campaignId/encounter-library'
      path: '/encounter-library'
      fullPath: '/campaigns/$campaignId/encounter-library'
      preLoaderRoute: typeof CampaignsCampaignIdEncounterLibraryRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/workspace/': {
      id: '/campaigns/$campaignId/workspace/'
      path: '/'
      fullPath: '/campaigns/$campaignId/workspace/'
      preLoaderRoute: typeof CampaignsCampaignIdWorkspaceIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdWorkspaceRoute
    }
    '/campaigns/$campaignId/workspace/sessions': {
      id: '/campaigns/$campaignId/workspace/sessions'
      path: '/sessions'
      fullPath: '/campaigns/$campaignId/workspace/sessions'
      preLoaderRoute: typeof CampaignsCampaignIdWorkspaceSessionsRouteImport
      parentRoute: typeof CampaignsCampaignIdWorkspaceRoute
    }
    '/campaigns/$campaignId/workspace/secrets': {
      id: '/campaigns/$campaignId/workspace/secrets'
      path: '/secrets'
      fullPath: '/campaigns/$campaignId/workspace/secrets'
      preLoaderRoute: typeof CampaignsCampaignIdWorkspaceSecretsRouteImport
      parentRoute: typeof CampaignsCampaignIdWorkspaceRoute
    }
    '/campaigns/$campaignId/workspace/scene-notes': {
      id: '/campaigns/$campaignId/workspace/scene-notes'
      path: '/scene-notes'
      fullPath: '/campaigns/$campaignId/workspace/scene-notes'
      preLoaderRoute: typeof CampaignsCampaignIdWorkspaceSceneNotesRouteImport
      parentRoute: typeof CampaignsCampaignIdWorkspaceRoute
    }
    '/campaigns/$campaignId/workspace/player-characters': {
      id: '/campaigns/$campaignId/workspace/player-characters'
      path: '/player-characters'
      fullPath: '/campaigns/$campaignId/workspace/player-characters'
      preLoaderRoute: typeof CampaignsCampaignIdWorkspacePlayerCharactersRouteImport
      parentRoute: typeof CampaignsCampaignIdWorkspaceRoute
    }
    '/campaigns/$campaignId/workspace/npcs': {
      id: '/campaigns/$campaignId/workspace/npcs'
      path: '/npcs'
      fullPath: '/campaigns/$campaignId/workspace/npcs'
      preLoaderRoute: typeof CampaignsCampaignIdWorkspaceNpcsRouteImport
      parentRoute: typeof CampaignsCampaignIdWorkspaceRoute
    }
    '/campaigns/$campaignId/workspace/log': {
      id: '/campaigns/$campaignId/workspace/log'
      path: '/log'
      fullPath: '/campaigns/$campaignId/workspace/log'
      preLoaderRoute: typeof CampaignsCampaignIdWorkspaceLogRouteImport
      parentRoute: typeof CampaignsCampaignIdWorkspaceRoute
    }
    '/campaigns/$campaignId/workspace/encounters': {
      id: '/campaigns/$campaignId/workspace/encounters'
      path: '/encounters'
      fullPath: '/campaigns/$campaignId/workspace/encounters'
      preLoaderRoute: typeof CampaignsCampaignIdWorkspaceEncountersRouteImport
      parentRoute: typeof CampaignsCampaignIdWorkspaceRoute
    }
    '/campaigns/$campaignId/workspace/dm-screen': {
      id: '/campaigns/$campaignId/workspace/dm-screen'
      path: '/dm-screen'
      fullPath: '/campaigns/$campaignId/workspace/dm-screen'
      preLoaderRoute: typeof CampaignsCampaignIdWorkspaceDmScreenRouteImport
      parentRoute: typeof CampaignsCampaignIdWorkspaceRoute
    }
    '/campaigns/$campaignId/workspace/sessions/': {
      id: '/campaigns/$campaignId/workspace/sessions/'
      path: '/'
      fullPath: '/campaigns/$campaignId/workspace/sessions/'
      preLoaderRoute: typeof CampaignsCampaignIdWorkspaceSessionsIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdWorkspaceSessionsRoute
    }
    '/campaigns/$campaignId/workspace/player-characters/': {
      id: '/campaigns/$campaignId/workspace/player-characters/'
      path: '/'
      fullPath: '/campaigns/$campaignId/workspace/player-characters/'
      preLoaderRoute: typeof CampaignsCampaignIdWorkspacePlayerCharactersIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdWorkspacePlayerCharactersRoute
    }
    '/campaigns/$campaignId/workspace/sessions/$sessionId': {
      id: '/campaigns/$campaignId/workspace/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/campaigns/$campaignId/workspace/sessions/$sessionId'
      preLoaderRoute: typeof CampaignsCampaignIdWorkspaceSessionsSessionIdRouteImport
      parentRoute: typeof CampaignsCampaignIdWorkspaceSessionsRoute
    }
    '/campaigns/$campaignId/workspace/player-characters/$playerCharacterId': {
      id: '/campaigns/$campaignId/workspace/player-characters/$playerCharacterId'
      path: '/$playerCharacterId'
      fullPath: '/campaigns/$campaignId/workspace/player-characters/$playerCharacterId'
      preLoaderRoute: typeof CampaignsCampaignIdWorkspacePlayerCharactersPlayerCharacterIdRouteImport
      parentRoute: typeof CampaignsCampaignIdWorkspacePlayerCharactersRoute
    }
  }
}

interface CampaignsCampaignIdWorkspacePlayerCharactersRouteChildren {
  CampaignsCampaignIdWorkspacePlayerCharactersPlayerCharacterIdRoute: typeof CampaignsCampaignIdWorkspacePlayerCharactersPlayerCharacterIdRoute
  CampaignsCampaignIdWorkspacePlayerCharactersIndexRoute: typeof CampaignsCampaignIdWorkspacePlayerCharactersIndexRoute
}

const CampaignsCampaignIdWorkspacePlayerCharactersRouteChildren: CampaignsCampaignIdWorkspacePlayerCharactersRouteChildren =
  {
    CampaignsCampaignIdWorkspacePlayerCharactersPlayerCharacterIdRoute:
      CampaignsCampaignIdWorkspacePlayerCharactersPlayerCharacterIdRoute,
    CampaignsCampaignIdWorkspacePlayerCharactersIndexRoute:
      CampaignsCampaignIdWorkspacePlayerCharactersIndexRoute,
  }

const CampaignsCampaignIdWorkspacePlayerCharactersRouteWithChildren =
  CampaignsCampaignIdWorkspacePlayerCharactersRoute._addFileChildren(
    CampaignsCampaignIdWorkspacePlayerCharactersRouteChildren,
  )

interface CampaignsCampaignIdWorkspaceSessionsRouteChildren {
  CampaignsCampaignIdWorkspaceSessionsSessionIdRoute: typeof CampaignsCampaignIdWorkspaceSessionsSessionIdRoute
  CampaignsCampaignIdWorkspaceSessionsIndexRoute: typeof CampaignsCampaignIdWorkspaceSessionsIndexRoute
}

const CampaignsCampaignIdWorkspaceSessionsRouteChildren: CampaignsCampaignIdWorkspaceSessionsRouteChildren =
  {
    CampaignsCampaignIdWorkspaceSessionsSessionIdRoute:
      CampaignsCampaignIdWorkspaceSessionsSessionIdRoute,
    CampaignsCampaignIdWorkspaceSessionsIndexRoute:
      CampaignsCampaignIdWorkspaceSessionsIndexRoute,
  }

const CampaignsCampaignIdWorkspaceSessionsRouteWithChildren =
  CampaignsCampaignIdWorkspaceSessionsRoute._addFileChildren(
    CampaignsCampaignIdWorkspaceSessionsRouteChildren,
  )

interface CampaignsCampaignIdWorkspaceRouteChildren {
  CampaignsCampaignIdWorkspaceDmScreenRoute: typeof CampaignsCampaignIdWorkspaceDmScreenRoute
  CampaignsCampaignIdWorkspaceEncountersRoute: typeof CampaignsCampaignIdWorkspaceEncountersRoute
  CampaignsCampaignIdWorkspaceLogRoute: typeof CampaignsCampaignIdWorkspaceLogRoute
  CampaignsCampaignIdWorkspaceNpcsRoute: typeof CampaignsCampaignIdWorkspaceNpcsRoute
  CampaignsCampaignIdWorkspacePlayerCharactersRoute: typeof CampaignsCampaignIdWorkspacePlayerCharactersRouteWithChildren
  CampaignsCampaignIdWorkspaceSceneNotesRoute: typeof CampaignsCampaignIdWorkspaceSceneNotesRoute
  CampaignsCampaignIdWorkspaceSecretsRoute: typeof CampaignsCampaignIdWorkspaceSecretsRoute
  CampaignsCampaignIdWorkspaceSessionsRoute: typeof CampaignsCampaignIdWorkspaceSessionsRouteWithChildren
  CampaignsCampaignIdWorkspaceIndexRoute: typeof CampaignsCampaignIdWorkspaceIndexRoute
}

const CampaignsCampaignIdWorkspaceRouteChildren: CampaignsCampaignIdWorkspaceRouteChildren =
  {
    CampaignsCampaignIdWorkspaceDmScreenRoute:
      CampaignsCampaignIdWorkspaceDmScreenRoute,
    CampaignsCampaignIdWorkspaceEncountersRoute:
      CampaignsCampaignIdWorkspaceEncountersRoute,
    CampaignsCampaignIdWorkspaceLogRoute: CampaignsCampaignIdWorkspaceLogRoute,
    CampaignsCampaignIdWorkspaceNpcsRoute:
      CampaignsCampaignIdWorkspaceNpcsRoute,
    CampaignsCampaignIdWorkspacePlayerCharactersRoute:
      CampaignsCampaignIdWorkspacePlayerCharactersRouteWithChildren,
    CampaignsCampaignIdWorkspaceSceneNotesRoute:
      CampaignsCampaignIdWorkspaceSceneNotesRoute,
    CampaignsCampaignIdWorkspaceSecretsRoute:
      CampaignsCampaignIdWorkspaceSecretsRoute,
    CampaignsCampaignIdWorkspaceSessionsRoute:
      CampaignsCampaignIdWorkspaceSessionsRouteWithChildren,
    CampaignsCampaignIdWorkspaceIndexRoute:
      CampaignsCampaignIdWorkspaceIndexRoute,
  }

const CampaignsCampaignIdWorkspaceRouteWithChildren =
  CampaignsCampaignIdWorkspaceRoute._addFileChildren(
    CampaignsCampaignIdWorkspaceRouteChildren,
  )

interface CampaignsCampaignIdRouteChildren {
  CampaignsCampaignIdEncounterLibraryRoute: typeof CampaignsCampaignIdEncounterLibraryRoute
  CampaignsCampaignIdLoreSecretsDatabaseRoute: typeof CampaignsCampaignIdLoreSecretsDatabaseRoute
  CampaignsCampaignIdNpcDatabaseRoute: typeof CampaignsCampaignIdNpcDatabaseRoute
  CampaignsCampaignIdWorkspaceRoute: typeof CampaignsCampaignIdWorkspaceRouteWithChildren
  CampaignsCampaignIdIndexRoute: typeof CampaignsCampaignIdIndexRoute
}

const CampaignsCampaignIdRouteChildren: CampaignsCampaignIdRouteChildren = {
  CampaignsCampaignIdEncounterLibraryRoute:
    CampaignsCampaignIdEncounterLibraryRoute,
  CampaignsCampaignIdLoreSecretsDatabaseRoute:
    CampaignsCampaignIdLoreSecretsDatabaseRoute,
  CampaignsCampaignIdNpcDatabaseRoute: CampaignsCampaignIdNpcDatabaseRoute,
  CampaignsCampaignIdWorkspaceRoute:
    CampaignsCampaignIdWorkspaceRouteWithChildren,
  CampaignsCampaignIdIndexRoute: CampaignsCampaignIdIndexRoute,
}

const CampaignsCampaignIdRouteWithChildren =
  CampaignsCampaignIdRoute._addFileChildren(CampaignsCampaignIdRouteChildren)

interface CampaignsRouteChildren {
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRouteWithChildren
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsCampaignIdRoute: CampaignsCampaignIdRouteWithChildren,
  CampaignsIndexRoute: CampaignsIndexRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

interface MapsRouteChildren {
  MapsMapIdRoute: typeof MapsMapIdRoute
  MapsIndexRoute: typeof MapsIndexRoute
}

const MapsRouteChildren: MapsRouteChildren = {
  MapsMapIdRoute: MapsMapIdRoute,
  MapsIndexRoute: MapsIndexRoute,
}

const MapsRouteWithChildren = MapsRoute._addFileChildren(MapsRouteChildren)

interface RpgsRouteChildren {
  RpgsDndRoute: typeof RpgsDndRoute
  RpgsIndexRoute: typeof RpgsIndexRoute
}

const RpgsRouteChildren: RpgsRouteChildren = {
  RpgsDndRoute: RpgsDndRoute,
  RpgsIndexRoute: RpgsIndexRoute,
}

const RpgsRouteWithChildren = RpgsRoute._addFileChildren(RpgsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  MapsRoute: MapsRouteWithChildren,
  RpgsRoute: RpgsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
